title: 1000 Words Club
author: billy@1000wordsclub.com
email: info@1000wordsclub.com
description: >-
  Instant Camera Subscription Box
#baseurl: "/1000wc" # the subpath of your site, e.g. /blog
url: "1000wordsclub.com" # your site's origin, e.g. https://forestry.io
permalink: "/:title:output_ext"
# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
